### ISSUE TITLE
Wrap blacklist processing request in `try` block.

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/rain-api-core#131]
If there is a problem downloading the JWT Blacklist, this will manifest as confusing errors blocking downloads.

Need to handle that more safely.

https://github.com/asfadmin/rain-api-core/blob/d62cb461c7e250b144acd53d9985d576a3554d9e/rain_api_core/view_util.py#L169

**Comment by mckadesorensen** [comment]
https://github.com/asfadmin/rain-api-core/pull/138
