### ISSUE TITLE
No JWT + Restricted = Error. 

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/rain-api-core#78]
A user without a cookie, trying to access restricted data, will get this error:

```
Traceback (most recent call last):
File "/opt/python/chalice/app.py", line 1135, in _get_view_function_response
response = view_function(**function_args)
File "/var/task/app.py", line 612, in dynamic_url
u_in_g, new_user_profile = user_in_group(private_check, cookievars, user_profile, False)
TypeError: cannot unpack non-iterable bool object
```

Solution appears to be adding a second return value to this line:

https://github.com/asfadmin/rain-api-core/blob/c992f5ed865e26b53d7dd6b6019257f1fa417d12/rain_api_core/urs_util.py#L210

But the disembodied else block is also concerning:
https://github.com/asfadmin/rain-api-core/blob/master/rain_api_core/urs_util.py#L212

**Comment by benbart** [comment]
This:
https://github.com/asfadmin/rain-api-core/blob/master/rain_api_core/urs_util.py#L212
is a try...except...else block, you can see that described here: https://docs.python.org/3/tutorial/errors.html
